[project]
name = "calculator-agent"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "agentgymrl",
    "pydantic>=2.10.6",
    "python-dotenv>=1.1.0",
]

[tool.uv.sources]
agentgymrl = { path = "../../" }
